#!/bin/sh

set -e

case "$1" in
    configure)
        if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ] && command -v rsyslogd >/dev/null 2>&1; then
            systemctl restart rsyslog >/dev/null 2>&1 || true
        fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
